### PR TITLE
heckle.cabal: bump to latest optparse-applicative-0.13

### PR DESCRIPTION
**Pull request by trofi**

### CODE REVIEW

**Comment by 2016rshah** [comment]
I checked this out locally, and building `stack build` failed with the following error:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for heckle-2.0.1.9:
    optparse-applicative-0.12.1.0 must match >=0.13.0.0 && <0.14.0.0 (latest applicable is 0.13.0.0)

Plan construction failed.
```

**Comment by trofi** [comment]
Oh, I see. lts stackage contains optparse-applicative-0.12 version.
I've added support for 0.12 with minor '#ifdef'-ery.

**Comment by 2016rshah** [comment]
Maybe this is a crazy question, but what are the benefits of upgrading to `optparse-applicative-0.13` and why do we need to do it?

**Comment by trofi** [comment]
In Gentoo ( where we package heckle: https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-haskell/heckle/heckle-2.0.1.9-r1.ebuild ) we usually try to maintain single version for each package provided.

Quite a few packages started using optparse-applicative-0.13: for example stack itself uses `0.13`, diagrams use `0.13`.

Given that API changes are minor we've decided to port all Gentoo packages to
optparse-applicative-0.13 to avoid having multiple versions of the same library on user's system.

Stackage nightly also has at optparse-applicative-0.13: https://www.stackage.org/nightly-2017-01-25/package/optparse-applicative-0.13.0.0

**Comment by 2016rshah** [comment]
That makes a lot of sense, thank you for explaining!

**Pull request merged**
